### ISSUE TITLE
Duplicate nested files

### ISSUE THREAD

**Issue by demiavaliani** [radkinz/snow.js#1]
A great library, first of all. I have one question, just out of curiosity. Why under root demo folder, there are so many duplicate files nested?
![image](https://user-images.githubusercontent.com/33201116/143490130-fef200c9-e3bd-4fe6-93ac-48bbc14cbe23.png)

**Comment by radkinz** [comment]
Hi there! Since this was my first JavaScript library, I made the mistake of downloading my own library into the demo folder, as I was testing things out. However, I think I fixed the issue by removing those files, and I updated the github repo + npm library with the *hopefully* cleaner version. Thanks for bringing this to my attention!

**Comment by demiavaliani** [comment]
Yup, looks beautiful now. Thanks!
